name: Test
version: '${project.version}'
main: de.flamex.test.Test
api-version: 1.18
commands:
  unban:
    description: Unban a player
    usage: /unban <username>
    permission: minecraft.command.pardon
  lp:
    description: Locate a player
    usage: /lp <username>
    permission: minecraft.command.stop